version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: django_test_image:6
    networks:
      - network
    volumes:
      - static-volume:/home/pragmatic/staticfiles
      - media-volume:/home/pragmatic/media
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
  mariadb:
    image: mariadb:11.0
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: password1234
      MYSQL_ROOT_PASSWORD: password1234


networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

